<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <title>README</title>
  <style type="text/css">
      code{white-space: pre-wrap;}
      span.smallcaps{font-variant: small-caps;}
      span.underline{text-decoration: underline;}
      div.column{display: inline-block; vertical-align: top; width: 50%;}
  </style>
  <style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
  </style>
</head>
<body>
<h1 id="verror-rich-javascript-errors">verror: rich JavaScript errors</h1>
<p>This module provides several classes in support of Joyent’s <a href="http://www.joyent.com/developers/node/design/errors">Best Practices for Error Handling in Node.js</a>. If you find any of the behavior here confusing or surprising, check out that document first.</p>
<p>The error classes here support:</p>
<ul>
<li>printf-style arguments for the message</li>
<li>chains of causes</li>
<li>properties to provide extra information about the error</li>
<li>creating your own subclasses that support all of these</li>
</ul>
<p>The classes here are:</p>
<ul>
<li><strong>VError</strong>, for chaining errors while preserving each one’s error message. This is useful in servers and command-line utilities when you want to propagate an error up a call stack, but allow various levels to add their own context. See examples below.</li>
<li><strong>WError</strong>, for wrapping errors while hiding the lower-level messages from the top-level error. This is useful for API endpoints where you don’t want to expose internal error messages, but you still want to preserve the error chain for logging and debugging.</li>
<li><strong>SError</strong>, which is just like VError but interprets printf-style arguments more strictly.</li>
<li><strong>MultiError</strong>, which is just an Error that encapsulates one or more other errors. (This is used for parallel operations that return several errors.)</li>
</ul>
<h1 id="quick-start">Quick start</h1>
<p>First, install the package:</p>
<pre><code>npm install verror</code></pre>
<p>If nothing else, you can use VError as a drop-in replacement for the built-in JavaScript Error class, with the addition of printf-style messages:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode javascript"><code class="sourceCode javascript"><a class="sourceLine" id="cb2-1" title="1"><span class="kw">var</span> err <span class="op">=</span> <span class="kw">new</span> <span class="at">VError</span>(<span class="st">&#39;missing file: &quot;%s&quot;&#39;</span><span class="op">,</span> <span class="st">&#39;/etc/passwd&#39;</span>)<span class="op">;</span></a>
<a class="sourceLine" id="cb2-2" title="2"><span class="va">console</span>.<span class="at">log</span>(<span class="va">err</span>.<span class="at">message</span>)<span class="op">;</span></a></code></pre></div>
<p>This prints:</p>
<pre><code>missing file: &quot;/etc/passwd&quot;</code></pre>
<p>You can also pass a <code>cause</code> argument, which is any other Error object:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode javascript"><code class="sourceCode javascript"><a class="sourceLine" id="cb4-1" title="1"><span class="kw">var</span> fs <span class="op">=</span> <span class="at">require</span>(<span class="st">&#39;fs&#39;</span>)<span class="op">;</span></a>
<a class="sourceLine" id="cb4-2" title="2"><span class="kw">var</span> filename <span class="op">=</span> <span class="st">&#39;/nonexistent&#39;</span><span class="op">;</span></a>
<a class="sourceLine" id="cb4-3" title="3"><span class="va">fs</span>.<span class="at">stat</span>(filename<span class="op">,</span> <span class="kw">function</span> (err1) <span class="op">{</span></a>
<a class="sourceLine" id="cb4-4" title="4">    <span class="kw">var</span> err2 <span class="op">=</span> <span class="kw">new</span> <span class="at">VError</span>(err1<span class="op">,</span> <span class="st">&#39;stat &quot;%s&quot;&#39;</span><span class="op">,</span> filename)<span class="op">;</span></a>
<a class="sourceLine" id="cb4-5" title="5">    <span class="va">console</span>.<span class="at">error</span>(<span class="va">err2</span>.<span class="at">message</span>)<span class="op">;</span></a>
<a class="sourceLine" id="cb4-6" title="6"><span class="op">}</span>)<span class="op">;</span></a></code></pre></div>
<p>This prints out:</p>
<pre><code>stat &quot;/nonexistent&quot;: ENOENT, stat &#39;/nonexistent&#39;</code></pre>
<p>which resembles how Unix programs typically report errors:</p>
<pre><code>$ sort /nonexistent
sort: open failed: /nonexistent: No such file or directory</code></pre>
<p>To match the Unixy feel, when you print out the error, just prepend the program’s name to the VError’s <code>message</code>. Or just call <a href="https://github.com/joyent/node-cmdutil">node-cmdutil.fail(your_verror)</a>, which does this for you.</p>
<p>You can get the next-level Error using <code>err.cause()</code>:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode javascript"><code class="sourceCode javascript"><a class="sourceLine" id="cb7-1" title="1"><span class="va">console</span>.<span class="at">error</span>(<span class="va">err2</span>.<span class="at">cause</span>().<span class="at">message</span>)<span class="op">;</span></a></code></pre></div>
<p>prints:</p>
<pre><code>ENOENT, stat &#39;/nonexistent&#39;</code></pre>
<p>Of course, you can chain these as many times as you want, and it works with any kind of Error:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode javascript"><code class="sourceCode javascript"><a class="sourceLine" id="cb9-1" title="1"><span class="kw">var</span> err1 <span class="op">=</span> <span class="kw">new</span> <span class="at">Error</span>(<span class="st">&#39;No such file or directory&#39;</span>)<span class="op">;</span></a>
<a class="sourceLine" id="cb9-2" title="2"><span class="kw">var</span> err2 <span class="op">=</span> <span class="kw">new</span> <span class="at">VError</span>(err1<span class="op">,</span> <span class="st">&#39;failed to stat &quot;%s&quot;&#39;</span><span class="op">,</span> <span class="st">&#39;/junk&#39;</span>)<span class="op">;</span></a>
<a class="sourceLine" id="cb9-3" title="3"><span class="kw">var</span> err3 <span class="op">=</span> <span class="kw">new</span> <span class="at">VError</span>(err2<span class="op">,</span> <span class="st">&#39;request failed&#39;</span>)<span class="op">;</span></a>
<a class="sourceLine" id="cb9-4" title="4"><span class="va">console</span>.<span class="at">error</span>(<span class="va">err3</span>.<span class="at">message</span>)<span class="op">;</span></a></code></pre></div>
<p>This prints:</p>
<pre><code>request failed: failed to stat &quot;/junk&quot;: No such file or directory</code></pre>
<p>The idea is that each layer in the stack annotates the error with a description of what it was doing. The end result is a message that explains what happened at each level.</p>
<p>You can also decorate Error objects with additional information so that callers can not only handle each kind of error differently, but also construct their own error messages (e.g., to localize them, format them, group them by type, and so on). See the example below.</p>
<h1 id="deeper-dive">Deeper dive</h1>
<p>The two main goals for VError are:</p>
<ul>
<li><strong>Make it easy to construct clear, complete error messages intended for people.</strong> Clear error messages greatly improve both user experience and debuggability, so we wanted to make it easy to build them. That’s why the constructor takes printf-style arguments.</li>
<li><strong>Make it easy to construct objects with programmatically-accessible metadata</strong> (which we call <em>informational properties</em>). Instead of just saying “connection refused while connecting to 192.168.1.2:80”, you can add properties like <code>"ip": "192.168.1.2"</code> and <code>"tcpPort": 80</code>. This can be used for feeding into monitoring systems, analyzing large numbers of Errors (as from a log file), or localizing error messages.</li>
</ul>
<p>To really make this useful, it also needs to be easy to compose Errors: higher-level code should be able to augment the Errors reported by lower-level code to provide a more complete description of what happened. Instead of saying “connection refused”, you can say “operation X failed: connection refused”. That’s why VError supports <code>causes</code>.</p>
<p>In order for all this to work, programmers need to know that it’s generally safe to wrap lower-level Errors with higher-level ones. If you have existing code that handles Errors produced by a library, you should be able to wrap those Errors with a VError to add information without breaking the error handling code. There are two obvious ways that this could break such consumers:</p>
<ul>
<li>The error’s name might change. People typically use <code>name</code> to determine what kind of Error they’ve got. To ensure compatibility, you can create VErrors with custom names, but this approach isn’t great because it prevents you from representing complex failures. For this reason, VError provides <code>findCauseByName</code>, which essentially asks: does this Error <em>or any of its causes</em> have this specific type? If error handling code uses <code>findCauseByName</code>, then subsystems can construct very specific causal chains for debuggability and still let people handle simple cases easily. There’s an example below.</li>
<li>The error’s properties might change. People often hang additional properties off of Error objects. If we wrap an existing Error in a new Error, those properties would be lost unless we copied them. But there are a variety of both standard and non-standard Error properties that should <em>not</em> be copied in this way: most obviously <code>name</code>, <code>message</code>, and <code>stack</code>, but also <code>fileName</code>, <code>lineNumber</code>, and a few others. Plus, it’s useful for some Error subclasses to have their own private properties – and there’d be no way to know whether these should be copied. For these reasons, VError first-classes these information properties. You have to provide them in the constructor, you can only fetch them with the <code>info()</code> function, and VError takes care of making sure properties from causes wind up in the <code>info()</code> output.</li>
</ul>
<p>Let’s put this all together with an example from the node-fast RPC library. node-fast implements a simple RPC protocol for Node programs. There’s a server and client interface, and clients make RPC requests to servers. Let’s say the server fails with an UnauthorizedError with message “user ‘bob’ is not authorized”. The client wraps all server errors with a FastServerError. The client also wraps all request errors with a FastRequestError that includes the name of the RPC call being made. The result of this failed RPC might look like this:</p>
<pre><code>name: FastRequestError
message: &quot;request failed: server error: user &#39;bob&#39; is not authorized&quot;
rpcMsgid: &lt;unique identifier for this request&gt;
rpcMethod: GetObject
cause:
    name: FastServerError
    message: &quot;server error: user &#39;bob&#39; is not authorized&quot;
    cause:
        name: UnauthorizedError
        message: &quot;user &#39;bob&#39; is not authorized&quot;
        rpcUser: &quot;bob&quot;</code></pre>
<p>When the caller uses <code>VError.info()</code>, the information properties are collapsed so that it looks like this:</p>
<pre><code>message: &quot;request failed: server error: user &#39;bob&#39; is not authorized&quot;
rpcMsgid: &lt;unique identifier for this request&gt;
rpcMethod: GetObject
rpcUser: &quot;bob&quot;</code></pre>
<p>Taking this apart:</p>
<ul>
<li>The error’s message is a complete description of the problem. The caller can report this directly to its caller, which can potentially make its way back to an end user (if appropriate). It can also be logged.</li>
<li>The caller can tell that the request failed on the server, rather than as a result of a client problem (e.g., failure to serialize the request), a transport problem (e.g., failure to connect to the server), or something else (e.g., a timeout). They do this using <code>findCauseByName('FastServerError')</code> rather than checking the <code>name</code> field directly.</li>
<li>If the caller logs this error, the logs can be analyzed to aggregate errors by cause, by RPC method name, by user, or whatever. Or the error can be correlated with other events for the same rpcMsgid.</li>
<li>It wasn’t very hard for any part of the code to contribute to this Error. Each part of the stack has just a few lines to provide exactly what it knows, with very little boilerplate.</li>
</ul>
<p>It’s not expected that you’d use these complex forms all the time. Despite supporting the complex case above, you can still just do:</p>
<p>new VError(“my service isn’t working”);</p>
<p>for the simple cases.</p>
<h1 id="reference-verror-werror-serror">Reference: VError, WError, SError</h1>
<p>VError, WError, and SError are convenient drop-in replacements for <code>Error</code> that support printf-style arguments, first-class causes, informational properties, and other useful features.</p>
<h2 id="constructors">Constructors</h2>
<p>The VError constructor has several forms:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode javascript"><code class="sourceCode javascript"><a class="sourceLine" id="cb13-1" title="1"><span class="co">/*</span></a>
<a class="sourceLine" id="cb13-2" title="2"><span class="co"> * This is the most general form.  You can specify any supported options</span></a>
<a class="sourceLine" id="cb13-3" title="3"><span class="co"> * (including &quot;cause&quot; and &quot;info&quot;) this way.</span></a>
<a class="sourceLine" id="cb13-4" title="4"><span class="co"> */</span></a>
<a class="sourceLine" id="cb13-5" title="5"><span class="kw">new</span> <span class="at">VError</span>(options<span class="op">,</span> <span class="va">sprintf_args</span>...)</a>
<a class="sourceLine" id="cb13-6" title="6"></a>
<a class="sourceLine" id="cb13-7" title="7"><span class="co">/*</span></a>
<a class="sourceLine" id="cb13-8" title="8"><span class="co"> * This is a useful shorthand when the only option you need is &quot;cause&quot;.</span></a>
<a class="sourceLine" id="cb13-9" title="9"><span class="co"> */</span></a>
<a class="sourceLine" id="cb13-10" title="10"><span class="kw">new</span> <span class="at">VError</span>(cause<span class="op">,</span> <span class="va">sprintf_args</span>...)</a>
<a class="sourceLine" id="cb13-11" title="11"></a>
<a class="sourceLine" id="cb13-12" title="12"><span class="co">/*</span></a>
<a class="sourceLine" id="cb13-13" title="13"><span class="co"> * This is a useful shorthand when you don&#39;t need any options at all.</span></a>
<a class="sourceLine" id="cb13-14" title="14"><span class="co"> */</span></a>
<a class="sourceLine" id="cb13-15" title="15"><span class="kw">new</span> <span class="at">VError</span>(<span class="va">sprintf_args</span>...)</a></code></pre></div>
<p>All of these forms construct a new VError that behaves just like the built-in JavaScript <code>Error</code> class, with some additional methods described below.</p>
<p>In the first form, <code>options</code> is a plain object with any of the following optional properties:</p>
<table>
<colgroup>
<col style="width: 41%" />
<col style="width: 41%" />
<col style="width: 17%" />
</colgroup>
<thead>
<tr class="header">
<th>Option name</th>
<th>Type</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>name</code></td>
<td>string</td>
<td>Describes what kind of error this is. This is intended for programmatic use to distinguish between different kinds of errors. Note that in modern versions of Node.js, this name is ignored in the <code>stack</code> property value, but callers can still use the <code>name</code> property to get at it.</td>
</tr>
<tr class="even">
<td><code>cause</code></td>
<td>any Error object</td>
<td>Indicates that the new error was caused by <code>cause</code>. See <code>cause()</code> below. If unspecified, the cause will be <code>null</code>.</td>
</tr>
<tr class="odd">
<td><code>strict</code></td>
<td>boolean</td>
<td>If true, then <code>null</code> and <code>undefined</code> values in <code>sprintf_args</code> are passed through to <code>sprintf()</code>. Otherwise, these are replaced with the strings <code>'null'</code>, and ‘<code>undefined</code>’, respectively.</td>
</tr>
<tr class="even">
<td><code>constructorOpt</code></td>
<td>function</td>
<td>If specified, then the stack trace for this error ends at function <code>constructorOpt</code>. Functions called by <code>constructorOpt</code> will not show up in the stack. This is useful when this class is subclassed.</td>
</tr>
<tr class="odd">
<td><code>info</code></td>
<td>object</td>
<td>Specifies arbitrary informational properties that are available through the <code>VError.info(err)</code> static class method. See that method for details.</td>
</tr>
</tbody>
</table>
<p>The second form is equivalent to using the first form with the specified <code>cause</code> as the error’s cause. This form is distinguished from the first form because the first argument is an Error.</p>
<p>The third form is equivalent to using the first form with all default option values. This form is distinguished from the other forms because the first argument is not an object or an Error.</p>
<p>The <code>WError</code> constructor is used exactly the same way as the <code>VError</code> constructor. The <code>SError</code> constructor is also used the same way as the <code>VError</code> constructor except that in all cases, the <code>strict</code> property is overriden to `true.</p>
<h2 id="public-properties">Public properties</h2>
<p><code>VError</code>, <code>WError</code>, and <code>SError</code> all provide the same public properties as JavaScript’s built-in Error objects.</p>
<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 23%" />
<col style="width: 26%" />
</colgroup>
<thead>
<tr class="header">
<th>Property name</th>
<th>Type</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>name</code></td>
<td>string</td>
<td>Programmatically-usable name of the error.</td>
</tr>
<tr class="even">
<td><code>message</code></td>
<td>string</td>
<td>Human-readable summary of the failure. Programmatically-accessible details are provided through <code>VError.info(err)</code> class method.</td>
</tr>
<tr class="odd">
<td><code>stack</code></td>
<td>string</td>
<td>Human-readable stack trace where the Error was constructed.</td>
</tr>
</tbody>
</table>
<p>For all of these classes, the printf-style arguments passed to the constructor are processed with <code>sprintf()</code> to form a message. For <code>WError</code>, this becomes the complete <code>message</code> property. For <code>SError</code> and <code>VError</code>, this message is prepended to the message of the cause, if any (with a suitable separator), and the result becomes the <code>message</code> property.</p>
<p>The <code>stack</code> property is managed entirely by the underlying JavaScript implementation. It’s generally implemented using a getter function because constructing the human-readable stack trace is somewhat expensive.</p>
<h2 id="class-methods">Class methods</h2>
<p>The following methods are defined on the <code>VError</code> class and as exported functions on the <code>verror</code> module. They’re defined this way rather than using methods on VError instances so that they can be used on Errors not created with <code>VError</code>.</p>
<h3 id="verror.causeerr"><code>VError.cause(err)</code></h3>
<p>The <code>cause()</code> function returns the next Error in the cause chain for <code>err</code>, or <code>null</code> if there is no next error. See the <code>cause</code> argument to the constructor. Errors can have arbitrarily long cause chains. You can walk the <code>cause</code> chain by invoking <code>VError.cause(err)</code> on each subsequent return value. If <code>err</code> is not a <code>VError</code>, the cause is <code>null</code>.</p>
<h3 id="verror.infoerr"><code>VError.info(err)</code></h3>
<p>Returns an object with all of the extra error information that’s been associated with this Error and all of its causes. These are the properties passed in using the <code>info</code> option to the constructor. Properties not specified in the constructor for this Error are implicitly inherited from this error’s cause.</p>
<p>These properties are intended to provide programmatically-accessible metadata about the error. For an error that indicates a failure to resolve a DNS name, informational properties might include the DNS name to be resolved, or even the list of resolvers used to resolve it. The values of these properties should generally be plain objects (i.e., consisting only of null, undefined, numbers, booleans, strings, and objects and arrays containing only other plain objects).</p>
<h3 id="verror.fullstackerr"><code>VError.fullStack(err)</code></h3>
<p>Returns a string containing the full stack trace, with all nested errors recursively reported as <code>'caused by:' + err.stack</code>.</p>
<h3 id="verror.findcausebynameerr-name"><code>VError.findCauseByName(err, name)</code></h3>
<p>The <code>findCauseByName()</code> function traverses the cause chain for <code>err</code>, looking for an error whose <code>name</code> property matches the passed in <code>name</code> value. If no match is found, <code>null</code> is returned.</p>
<p>If all you want is to know <em>whether</em> there’s a cause (and you don’t care what it is), you can use <code>VError.hasCauseWithName(err, name)</code>.</p>
<p>If a vanilla error or a non-VError error is passed in, then there is no cause chain to traverse. In this scenario, the function will check the <code>name</code> property of only <code>err</code>.</p>
<h3 id="verror.hascausewithnameerr-name"><code>VError.hasCauseWithName(err, name)</code></h3>
<p>Returns true if and only if <code>VError.findCauseByName(err, name)</code> would return a non-null value. This essentially determines whether <code>err</code> has any cause in its cause chain that has name <code>name</code>.</p>
<h3 id="verror.errorfromlisterrors"><code>VError.errorFromList(errors)</code></h3>
<p>Given an array of Error objects (possibly empty), return a single error representing the whole collection of errors. If the list has:</p>
<ul>
<li>0 elements, returns <code>null</code></li>
<li>1 element, returns the sole error</li>
<li>more than 1 element, returns a MultiError referencing the whole list</li>
</ul>
<p>This is useful for cases where an operation may produce any number of errors, and you ultimately want to implement the usual <code>callback(err)</code> pattern. You can accumulate the errors in an array and then invoke <code>callback(VError.errorFromList(errors))</code> when the operation is complete.</p>
<h3 id="verror.errorforeacherr-func"><code>VError.errorForEach(err, func)</code></h3>
<p>Convenience function for iterating an error that may itself be a MultiError.</p>
<p>In all cases, <code>err</code> must be an Error. If <code>err</code> is a MultiError, then <code>func</code> is invoked as <code>func(errorN)</code> for each of the underlying errors of the MultiError. If <code>err</code> is any other kind of error, <code>func</code> is invoked once as <code>func(err)</code>. In all cases, <code>func</code> is invoked synchronously.</p>
<p>This is useful for cases where an operation may produce any number of warnings that may be encapsulated with a MultiError – but may not be.</p>
<p>This function does not iterate an error’s cause chain.</p>
<h2 id="examples">Examples</h2>
<p>The “Demo” section above covers several basic cases. Here’s a more advanced case:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode javascript"><code class="sourceCode javascript"><a class="sourceLine" id="cb14-1" title="1"><span class="kw">var</span> err1 <span class="op">=</span> <span class="kw">new</span> <span class="at">VError</span>(<span class="st">&#39;something bad happened&#39;</span>)<span class="op">;</span></a>
<a class="sourceLine" id="cb14-2" title="2"><span class="co">/* ... */</span></a>
<a class="sourceLine" id="cb14-3" title="3"><span class="kw">var</span> err2 <span class="op">=</span> <span class="kw">new</span> <span class="at">VError</span>(<span class="op">{</span></a>
<a class="sourceLine" id="cb14-4" title="4">    <span class="st">&#39;name&#39;</span><span class="op">:</span> <span class="st">&#39;ConnectionError&#39;</span><span class="op">,</span></a>
<a class="sourceLine" id="cb14-5" title="5">    <span class="st">&#39;cause&#39;</span><span class="op">:</span> err1<span class="op">,</span></a>
<a class="sourceLine" id="cb14-6" title="6">    <span class="st">&#39;info&#39;</span><span class="op">:</span> <span class="op">{</span></a>
<a class="sourceLine" id="cb14-7" title="7">        <span class="st">&#39;errno&#39;</span><span class="op">:</span> <span class="st">&#39;ECONNREFUSED&#39;</span><span class="op">,</span></a>
<a class="sourceLine" id="cb14-8" title="8">        <span class="st">&#39;remote_ip&#39;</span><span class="op">:</span> <span class="st">&#39;127.0.0.1&#39;</span><span class="op">,</span></a>
<a class="sourceLine" id="cb14-9" title="9">        <span class="st">&#39;port&#39;</span><span class="op">:</span> <span class="dv">215</span></a>
<a class="sourceLine" id="cb14-10" title="10">    <span class="op">}</span></a>
<a class="sourceLine" id="cb14-11" title="11"><span class="op">},</span> <span class="st">&#39;failed to connect to &quot;%s:%d&quot;&#39;</span><span class="op">,</span> <span class="st">&#39;127.0.0.1&#39;</span><span class="op">,</span> <span class="dv">215</span>)<span class="op">;</span></a>
<a class="sourceLine" id="cb14-12" title="12"></a>
<a class="sourceLine" id="cb14-13" title="13"><span class="va">console</span>.<span class="at">log</span>(<span class="va">err2</span>.<span class="at">message</span>)<span class="op">;</span></a>
<a class="sourceLine" id="cb14-14" title="14"><span class="va">console</span>.<span class="at">log</span>(<span class="va">err2</span>.<span class="at">name</span>)<span class="op">;</span></a>
<a class="sourceLine" id="cb14-15" title="15"><span class="va">console</span>.<span class="at">log</span>(<span class="va">VError</span>.<span class="at">info</span>(err2))<span class="op">;</span></a>
<a class="sourceLine" id="cb14-16" title="16"><span class="va">console</span>.<span class="at">log</span>(<span class="va">err2</span>.<span class="at">stack</span>)<span class="op">;</span></a></code></pre></div>
<p>This outputs:</p>
<pre><code>failed to connect to &quot;127.0.0.1:215&quot;: something bad happened
ConnectionError
{ errno: &#39;ECONNREFUSED&#39;, remote_ip: &#39;127.0.0.1&#39;, port: 215 }
ConnectionError: failed to connect to &quot;127.0.0.1:215&quot;: something bad happened
    at Object.&lt;anonymous&gt; (/home/dap/node-verror/examples/info.js:5:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3</code></pre>
<p>Information properties are inherited up the cause chain, with values at the top of the chain overriding same-named values lower in the chain. To continue that example:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode javascript"><code class="sourceCode javascript"><a class="sourceLine" id="cb16-1" title="1"><span class="kw">var</span> err3 <span class="op">=</span> <span class="kw">new</span> <span class="at">VError</span>(<span class="op">{</span></a>
<a class="sourceLine" id="cb16-2" title="2">    <span class="st">&#39;name&#39;</span><span class="op">:</span> <span class="st">&#39;RequestError&#39;</span><span class="op">,</span></a>
<a class="sourceLine" id="cb16-3" title="3">    <span class="st">&#39;cause&#39;</span><span class="op">:</span> err2<span class="op">,</span></a>
<a class="sourceLine" id="cb16-4" title="4">    <span class="st">&#39;info&#39;</span><span class="op">:</span> <span class="op">{</span></a>
<a class="sourceLine" id="cb16-5" title="5">        <span class="st">&#39;errno&#39;</span><span class="op">:</span> <span class="st">&#39;EBADREQUEST&#39;</span></a>
<a class="sourceLine" id="cb16-6" title="6">    <span class="op">}</span></a>
<a class="sourceLine" id="cb16-7" title="7"><span class="op">},</span> <span class="st">&#39;request failed&#39;</span>)<span class="op">;</span></a>
<a class="sourceLine" id="cb16-8" title="8"></a>
<a class="sourceLine" id="cb16-9" title="9"><span class="va">console</span>.<span class="at">log</span>(<span class="va">err3</span>.<span class="at">message</span>)<span class="op">;</span></a>
<a class="sourceLine" id="cb16-10" title="10"><span class="va">console</span>.<span class="at">log</span>(<span class="va">err3</span>.<span class="at">name</span>)<span class="op">;</span></a>
<a class="sourceLine" id="cb16-11" title="11"><span class="va">console</span>.<span class="at">log</span>(<span class="va">VError</span>.<span class="at">info</span>(err3))<span class="op">;</span></a>
<a class="sourceLine" id="cb16-12" title="12"><span class="va">console</span>.<span class="at">log</span>(<span class="va">err3</span>.<span class="at">stack</span>)<span class="op">;</span></a></code></pre></div>
<p>This outputs:</p>
<pre><code>request failed: failed to connect to &quot;127.0.0.1:215&quot;: something bad happened
RequestError
{ errno: &#39;EBADREQUEST&#39;, remote_ip: &#39;127.0.0.1&#39;, port: 215 }
RequestError: request failed: failed to connect to &quot;127.0.0.1:215&quot;: something bad happened
    at Object.&lt;anonymous&gt; (/home/dap/node-verror/examples/info.js:20:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3</code></pre>
<p>You can also print the complete stack trace of combined <code>Error</code>s by using <code>VError.fullStack(err).</code></p>
<div class="sourceCode" id="cb18"><pre class="sourceCode javascript"><code class="sourceCode javascript"><a class="sourceLine" id="cb18-1" title="1"><span class="kw">var</span> err1 <span class="op">=</span> <span class="kw">new</span> <span class="at">VError</span>(<span class="st">&#39;something bad happened&#39;</span>)<span class="op">;</span></a>
<a class="sourceLine" id="cb18-2" title="2"><span class="co">/* ... */</span></a>
<a class="sourceLine" id="cb18-3" title="3"><span class="kw">var</span> err2 <span class="op">=</span> <span class="kw">new</span> <span class="at">VError</span>(err1<span class="op">,</span> <span class="st">&#39;something really bad happened here&#39;</span>)<span class="op">;</span></a>
<a class="sourceLine" id="cb18-4" title="4"></a>
<a class="sourceLine" id="cb18-5" title="5"><span class="va">console</span>.<span class="at">log</span>(<span class="va">VError</span>.<span class="at">fullStack</span>(err2))<span class="op">;</span></a></code></pre></div>
<p>This outputs:</p>
<pre><code>VError: something really bad happened here: something bad happened
    at Object.&lt;anonymous&gt; (/home/dap/node-verror/examples/fullStack.js:5:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
caused by: VError: something bad happened
    at Object.&lt;anonymous&gt; (/home/dap/node-verror/examples/fullStack.js:3:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3</code></pre>
<p><code>VError.fullStack</code> is also safe to use on regular <code>Error</code>s, so feel free to use it whenever you need to extract the stack trace from an <code>Error</code>, regardless if it’s a <code>VError</code> or not.</p>
<h1 id="reference-multierror">Reference: MultiError</h1>
<p>MultiError is an Error class that represents a group of Errors. This is used when you logically need to provide a single Error, but you want to preserve information about multiple underying Errors. A common case is when you execute several operations in parallel and some of them fail.</p>
<p>MultiErrors are constructed as:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode javascript"><code class="sourceCode javascript"><a class="sourceLine" id="cb20-1" title="1"><span class="kw">new</span> <span class="at">MultiError</span>(error_list)</a></code></pre></div>
<p><code>error_list</code> is an array of at least one <code>Error</code> object.</p>
<p>The cause of the MultiError is the first error provided. None of the other <code>VError</code> options are supported. The <code>message</code> for a MultiError consists the <code>message</code> from the first error, prepended with a message indicating that there were other errors.</p>
<p>For example:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode javascript"><code class="sourceCode javascript"><a class="sourceLine" id="cb21-1" title="1">err <span class="op">=</span> <span class="kw">new</span> <span class="at">MultiError</span>([</a>
<a class="sourceLine" id="cb21-2" title="2">    <span class="kw">new</span> <span class="at">Error</span>(<span class="st">&#39;failed to resolve DNS name &quot;abc.example.com&quot;&#39;</span>)<span class="op">,</span></a>
<a class="sourceLine" id="cb21-3" title="3">    <span class="kw">new</span> <span class="at">Error</span>(<span class="st">&#39;failed to resolve DNS name &quot;def.example.com&quot;&#39;</span>)<span class="op">,</span></a>
<a class="sourceLine" id="cb21-4" title="4">])<span class="op">;</span></a>
<a class="sourceLine" id="cb21-5" title="5"></a>
<a class="sourceLine" id="cb21-6" title="6"><span class="va">console</span>.<span class="at">error</span>(<span class="va">err</span>.<span class="at">message</span>)<span class="op">;</span></a></code></pre></div>
<p>outputs:</p>
<pre><code>first of 2 errors: failed to resolve DNS name &quot;abc.example.com&quot;</code></pre>
<p>See the convenience function <code>VError.errorFromList</code>, which is sometimes simpler to use than this constructor.</p>
<h2 id="public-methods">Public methods</h2>
<h3 id="errors"><code>errors()</code></h3>
<p>Returns an array of the errors used to construct this MultiError.</p>
<h1 id="contributing">Contributing</h1>
<p>See separate <a href="CONTRIBUTING.md">contribution guidelines</a>.</p>
</body>
</html>
