Errors
------

NAN includes helpers for creating, throwing and catching Errors as much of this functionality varies across the supported versions of V8 and must be abstracted.

Note that an Error object is simply a specialized form of `v8::Value`.

Also consult the V8 Embedders Guide section on [Exceptions](https://developers.google.com/v8/embed#exceptions) for more information.

-   [**`Nan::Error()`**](#api_nan_error)
-   [**`Nan::RangeError()`**](#api_nan_range_error)
-   [**`Nan::ReferenceError()`**](#api_nan_reference_error)
-   [**`Nan::SyntaxError()`**](#api_nan_syntax_error)
-   [**`Nan::TypeError()`**](#api_nan_type_error)
-   [**`Nan::ThrowError()`**](#api_nan_throw_error)
-   [**`Nan::ThrowRangeError()`**](#api_nan_throw_range_error)
-   [**`Nan::ThrowReferenceError()`**](#api_nan_throw_reference_error)
-   [**`Nan::ThrowSyntaxError()`**](#api_nan_throw_syntax_error)
-   [**`Nan::ThrowTypeError()`**](#api_nan_throw_type_error)
-   [**`Nan::FatalException()`**](#api_nan_fatal_exception)
-   [**`Nan::ErrnoException()`**](#api_nan_errno_exception)
-   [**`Nan::TryCatch`**](#api_nan_try_catch)

<span id="api_nan_error"></span> \#\#\# Nan::Error()

Create a new Error object using the [v8::Exception](https://v8docs.nodesource.com/node-8.16/da/d6a/classv8_1_1_exception.html) class in a way that is compatible across the supported versions of V8.

Note that an Error object is simply a specialized form of `v8::Value`.

Signature:

    v8::Local<v8::Value> Nan::Error(const char *msg);
    v8::Local<v8::Value> Nan::Error(v8::Local<v8::String> msg);

<span id="api_nan_range_error"></span> \#\#\# Nan::RangeError()

Create a new RangeError object using the [v8::Exception](https://v8docs.nodesource.com/node-8.16/da/d6a/classv8_1_1_exception.html) class in a way that is compatible across the supported versions of V8.

Note that an RangeError object is simply a specialized form of `v8::Value`.

Signature:

    v8::Local<v8::Value> Nan::RangeError(const char *msg);
    v8::Local<v8::Value> Nan::RangeError(v8::Local<v8::String> msg);

<span id="api_nan_reference_error"></span> \#\#\# Nan::ReferenceError()

Create a new ReferenceError object using the [v8::Exception](https://v8docs.nodesource.com/node-8.16/da/d6a/classv8_1_1_exception.html) class in a way that is compatible across the supported versions of V8.

Note that an ReferenceError object is simply a specialized form of `v8::Value`.

Signature:

    v8::Local<v8::Value> Nan::ReferenceError(const char *msg);
    v8::Local<v8::Value> Nan::ReferenceError(v8::Local<v8::String> msg);

<span id="api_nan_syntax_error"></span> \#\#\# Nan::SyntaxError()

Create a new SyntaxError object using the [v8::Exception](https://v8docs.nodesource.com/node-8.16/da/d6a/classv8_1_1_exception.html) class in a way that is compatible across the supported versions of V8.

Note that an SyntaxError object is simply a specialized form of `v8::Value`.

Signature:

    v8::Local<v8::Value> Nan::SyntaxError(const char *msg);
    v8::Local<v8::Value> Nan::SyntaxError(v8::Local<v8::String> msg);

<span id="api_nan_type_error"></span> \#\#\# Nan::TypeError()

Create a new TypeError object using the [v8::Exception](https://v8docs.nodesource.com/node-8.16/da/d6a/classv8_1_1_exception.html) class in a way that is compatible across the supported versions of V8.

Note that an TypeError object is simply a specialized form of `v8::Value`.

Signature:

    v8::Local<v8::Value> Nan::TypeError(const char *msg);
    v8::Local<v8::Value> Nan::TypeError(v8::Local<v8::String> msg);

<span id="api_nan_throw_error"></span> \#\#\# Nan::ThrowError()

Throw an Error object (a specialized `v8::Value` as above) in the current context. If a `msg` is provided, a new Error object will be created.

Signature:

    void Nan::ThrowError(const char *msg);
    void Nan::ThrowError(v8::Local<v8::String> msg);
    void Nan::ThrowError(v8::Local<v8::Value> error);

<span id="api_nan_throw_range_error"></span> \#\#\# Nan::ThrowRangeError()

Throw an RangeError object (a specialized `v8::Value` as above) in the current context. If a `msg` is provided, a new RangeError object will be created.

Signature:

    void Nan::ThrowRangeError(const char *msg);
    void Nan::ThrowRangeError(v8::Local<v8::String> msg);
    void Nan::ThrowRangeError(v8::Local<v8::Value> error);

<span id="api_nan_throw_reference_error"></span> \#\#\# Nan::ThrowReferenceError()

Throw an ReferenceError object (a specialized `v8::Value` as above) in the current context. If a `msg` is provided, a new ReferenceError object will be created.

Signature:

    void Nan::ThrowReferenceError(const char *msg);
    void Nan::ThrowReferenceError(v8::Local<v8::String> msg);
    void Nan::ThrowReferenceError(v8::Local<v8::Value> error);

<span id="api_nan_throw_syntax_error"></span> \#\#\# Nan::ThrowSyntaxError()

Throw an SyntaxError object (a specialized `v8::Value` as above) in the current context. If a `msg` is provided, a new SyntaxError object will be created.

Signature:

    void Nan::ThrowSyntaxError(const char *msg);
    void Nan::ThrowSyntaxError(v8::Local<v8::String> msg);
    void Nan::ThrowSyntaxError(v8::Local<v8::Value> error);

<span id="api_nan_throw_type_error"></span> \#\#\# Nan::ThrowTypeError()

Throw an TypeError object (a specialized `v8::Value` as above) in the current context. If a `msg` is provided, a new TypeError object will be created.

Signature:

    void Nan::ThrowTypeError(const char *msg);
    void Nan::ThrowTypeError(v8::Local<v8::String> msg);
    void Nan::ThrowTypeError(v8::Local<v8::Value> error);

<span id="api_nan_fatal_exception"></span> \#\#\# Nan::FatalException()

Replaces `node::FatalException()` which has a different API across supported versions of Node. For use with [`Nan::TryCatch`](#api_nan_try_catch).

Signature:

    void Nan::FatalException(const Nan::TryCatch& try_catch);

<span id="api_nan_errno_exception"></span> \#\#\# Nan::ErrnoException()

Replaces `node::ErrnoException()` which has a different API across supported versions of Node.

Signature:

    v8::Local<v8::Value> Nan::ErrnoException(int errorno,
                                             const char* syscall = NULL,
                                             const char* message = NULL,
                                             const char* path = NULL);

<span id="api_nan_try_catch"></span> \#\#\# Nan::TryCatch

A simple wrapper around [`v8::TryCatch`](https://v8docs.nodesource.com/node-8.16/d4/dc6/classv8_1_1_try_catch.html) compatible with all supported versions of V8. Can be used as a direct replacement in most cases. See also [`Nan::FatalException()`](#api_nan_fatal_exception) for an internal use compatible with `node::FatalException`.

Signature:

    class Nan::TryCatch {
     public:
      Nan::TryCatch();

      bool HasCaught() const;

      bool CanContinue() const;

      v8::Local<v8::Value> ReThrow();

      v8::Local<v8::Value> Exception() const;

      // Nan::MaybeLocal for older versions of V8
      v8::MaybeLocal<v8::Value> StackTrace() const;

      v8::Local<v8::Message> Message() const;

      void Reset();

      void SetVerbose(bool value);

      void SetCaptureMessage(bool value);
    };
